server:
  port: ${SERVER_PORT:8082}

spring:
  datasource:
    url: jdbc:h2:mem:betmatchingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: bet-matching-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.sporty.group.commonlib.messaging.event
        spring.json.value.default.type: com.sporty.group.commonlib.messaging.event.EventOutcomeMessage

rocketmq:
  name-server: ${ROCKETMQ_NAME_SERVER:localhost:9876}
  producer:
    group: bet-matching-service-producer

app:
  messaging:
    event-outcomes-topic: event-outcomes
    bet-settlements-topic: bet-settlements
